# Generated by Django 3.2.20 on 2023-08-08 17:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_name', models.CharField(default='New Slot', max_length=50, unique=True)),
                ('max_slots', models.IntegerField()),
            ],
            options={
                'ordering': ['-max_slots'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('requested_date', models.DateField()),
                ('requested_time', models.CharField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30')], default='10:00', max_length=25)),
                ('status', models.CharField(choices=[('awaiting confirmation', 'awaiting confirmation'), ('booking accepted', 'booking accepted'), ('booking declined', 'booking declined'), ('booking expired', 'booking expired')], default='awaiting confirmation', max_length=25, unique=True)),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_reserved', to='book_a_slot.slot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='book_a_slot.user')),
            ],
            options={
                'ordering': ['-requested_time'],
            },
        ),
    ]
