# Generated by Django 3.2.20 on 2023-08-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_slot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.IntegerField(choices=[(1, '1 person'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people')], default=2),
        ),
    ]
