# Generated by Django 3.2.20 on 2023-08-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_slot', '0004_auto_20230811_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
