# Generated by Django 3.2.20 on 2023-08-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_a_slot', '0005_alter_booking_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('requested_date', 'requested_time', 'slot')},
        ),
    ]
