# Generated by Django 3.2.20 on 2023-08-25 08:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalogue', '0002_alter_productitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='item_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
