# Generated by Django 3.2.20 on 2023-08-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalogue', '0004_alter_productitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_type',
            field=models.IntegerField(
                choices=[
                    (0, 'Necklaces'),
                    (1, 'Bags'),
                    (2, 'Rings'),
                    (3, 'Bracelets'),
                    (4, 'Earrings'),
                    (5, 'New')], default=4),
        ),
    ]
